name: Repro

on:
  push:
    branches:
      - "**"
      - "master"

jobs:
  reprojob:
    name: build-on-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, windows-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
          dotnet-version: "3.1.x"
    - uses: actions/setup-dotnet@v1
      with:
          dotnet-version: "6.0.x"
          include-prerelease: true
    - run: dotnet --info
    - run: dotnet build SomeFunction
    - run: |
        brew tap azure/functions
        brew install azure-functions-core-tools@3
      if: ${{ matrix.os == 'macos-latest' }}
    - run: sudo apt-get install azure-functions-core-tools-3
      if: ${{ matrix.os == 'ubuntu-latest' }}
    - run: Install-Binary -Url "https://go.microsoft.com/fwlink/?linkid=2135274" -Name "func-cli-x64.msi"
      if: ${{ matrix.os == 'windows-latest' }}
    - run: .\func --version
